### ISSUE TITLE
last update broke the integration

### ISSUE THREAD

**Issue by Dolphin1220** [dupondje/nrgkick-ha#22]
after the last update (i don't know the exact version) there was an hint, that the new integration uses the official API, i don't know there is one ? after the restart from Home-Assistant, the integration was broken. i want to activate it again, but now he wants an url, a username and a password. what is this URL and the other things. There is no question about the serial-number form my nrg-kick.
I cant downgrade, or i don't know how, fact is the integration no longer works after this update. please fix it!!!

**Comment by dupondje** [comment]
There is now an official API for the NRGkick. You can enable that API via the NRGkick app.
You can also set an optional username and password in the app for the API.
Once that has been configured you can use that in the updated integration.

**Comment by Dolphin1220** [comment]
Thank you,

I have activated the API via APP, but this also requires a firmware 
update of the NRG-Kick, which is installed remotely by the manufacturer, 
this can take up to 3 weeks.

What should I enter for the URL? Is this the local IP of my NRK-Kick 
with http or https?

Perhaps you could also adapt the instructions, the old information with 
the serial number is still there. The help page at Homeassistant 
(https://www.home-assistant.io/integrations/nrgkick) does not yet exist 
either.

In any case, many thanks for this great integration, it really helps me 
a lot.


Kind regards
Andy


------ Originalnachricht ------
Von "dupondje" ***@***.***>
An "dupondje/nrgkick-ha" ***@***.***>
Cc "Dolphin1220" ***@***.***>; "Author" ***@***.***>
Datum 10.08.2024 17:07:38
Betreff Re: [dupondje/nrgkick-ha] last update broke the integration 
(Issue #22)

**Comment by fano0001** [comment]
Same for me, i habe to wait up to 17 Day due to the FW Update. Maybe a Hint in the readme is helpful die others to Check First the Version

**Comment by SchoergPet** [comment]
I have the same problem. Nrgkick integration broke.
I cannot find the possibility to enable the API within the NRGKick App.
Could please anyone explain how to do that?

**Comment by Dolphin1220** [comment]
Open the App and tap an these Symbol, here you can ask for the Firmware Update, this takes 2-3 Weeks, and then you can use the API:
![grafik](https://github.com/user-attachments/assets/af2212f7-927a-4e4c-9239-b708a8e42b66)

**Comment by SchoergPet** [comment]
Thanks for the help. My app shows, that it is now activated (without firmware update)
I'll test it the next days.

**Comment by SchoergPet** [comment]
It seems to work - I mean I see the device and all parameters. But I cannot adjust anything (switch on/off, set current and so on).
Any Idea what's wrong?

**Comment by SchoergPet** [comment]
Oh no! The new API based integration works only to read out parameters from the NRGKick-Gen2
The control of the device is not possible (again). No matter if I use authentication or not. I deleted the integration several times, configurated it new.... The device was always found, but the use of controls (pause on/off or currency settings) are not possible.


Can I have the previous NRGKick integration back? This was good for me.

**Comment by dupondje** [comment]
I have it running, and can perfectly change charging rate etc with the new API.
So it should be working 🤔

**Comment by thecem** [comment]
Short manual:

1. Delete the old integration
2. Reload in Hacs this repository.
3. Restart HA
4. Set in NrgKick app to JSON API, set user and pw, click save.
5. check that API circle is blue and JSON API is green checked.
6. Add the integration nrgkick and enter:
URL: http://your-nrgkick-privat-ip
User: your-user-name-for-the-nrgkick-local-api
Password: your-password-for-the-nrgkick-local-api

**Comment by aichingerk** [comment]
I also updated to the new API version. simple control is working but missing the sensor control_pilot_status, because i'm using the control from nrg kick through evcc and within evcc i made a third party loader, because there is no nativ support for nrgkick.
https://github.com/evcc-io/evcc/discussions/11656


i switched back to the old version fe18d84 through a full backup, because you only have one main brunch and no different version to switch. also all sensor names are different to the old one, and so i had to addapt all scripts, automations and helpers.

is it possible to make following change for your integration:
- Version integration
- activation for a backup "selction field" before the upgrade
- a choice whether to use the api or the websocket version

**Comment by Dolphin1220** [comment]
After the Upgrade everything works for me..

**Comment by thecem** [comment]
Did you tested if you are able to set the values via HA? For me it is not possible.

**Comment by dupondje** [comment]
> Did you tested if you are able to set the values via HA? For me it is not possible.

Yes, this works perfectly here. So weird it doesn't work for you.
Did you test manually via the API?

**Comment by thecem** [comment]
![IMG_2556](https://github.com/user-attachments/assets/be88c35b-0eb2-41c0-a92f-76ac68b1e084)

yes it is ack by 200 OK via web interface and via direct call to:

`http://192.168.1.6/control?current_set=10`

**Comment by thecem** [comment]
Version i have installed is:  713abc0. I configured with user/pw.

I would really propose to have both versions cloud and local like @aichingerk mentioned before, so every one could decide which version is best for. Since the API is not giving all needed features.

**Comment by SchoergPet** [comment]
I got it working now (almost). I can switch on and off (pause on/off) and set the aktual current.
Only change of phases (phasecount) is not possible.
How to do that. Is it necessary to pause NRGkick before changing from 1 to 3 phases? Or anything else to set before?
If I test it via App it works, but not in HA

![image](https://github.com/user-attachments/assets/09c6c552-c71d-4124-a4ae-f27afd9ac33e)

**Comment by dupondje** [comment]
> but missing the sensor control_pilot_status

Status is available in the new API.
`general_status` is the sensor

**Comment by dupondje** [comment]
> ![IMG_2556](https://private-user-images.githubusercontent.com/46648579/358232821-be88c35b-0eb2-41c0-a92f-76ac68b1e084.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NTY4ODYsIm5iZiI6MTcyMzc1NjU4NiwicGF0aCI6Ii80NjY0ODU3OS8zNTgyMzI4MjEtYmU4OGMzNWItMGViMi00MWMwLWE5MmYtNzZhYzY4YjFlMDg0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQyMTE2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTk0YjI4ZTRkNzQxN2EyODEyNGUwM2QwNzRlOTIzODM5NjMyMDA2YTI4NDBiMmM4MDYwZGI3MTJlMmFhOTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X7v53Dw_9V9G2c15cKE22W0KoHy1fPzJVKeEAFWRh9g)
> 
> yes it is ack by 200 OK via web interface and via direct call to:
> 
> `http://192.168.1.6/control?current_set=10`

Can you debug it further perhaps?
Cause HA should make the same call and it works here for example..

**Comment by dupondje** [comment]
> I got it working now (almost). I can switch on and off (pause on/off) and set the actual current.
> 
> Only change of phases (phasecount) is not possible. How to do that. Is it necessary to pause NRGkick before changing from 1 to 3 phases? Or anything else to set before?
> 
> If I test it via App it works, but not in HA
> 
> ![image](https://private-user-images.githubusercontent.com/149110925/358294501-09c6c552-c71d-4124-a4ae-f27afd9ac33e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NTY4ODYsIm5iZiI6MTcyMzc1NjU4NiwicGF0aCI6Ii8xNDkxMTA5MjUvMzU4Mjk0NTAxLTA5YzZjNTUyLWM3MWQtNDEyNC1hNGFlLWYyN2FmZDlhYzMzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQyMTE2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWU4ZTU1MTQyMDk2OTFlMDU5YTAzYmQ3MTg1MDc4N2YyZDc1NGQzODY1YjI1MmUzMWU1OTA0NDdlMTEzYWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IJeiz_eMSOD1rQsC3SqL8IA1lBY1lw4gAfHbMUv7cLY)

Phase switching enabled in the app?
And what happens when you manually try to change it via the API website?

**Comment by SchoergPet** [comment]
Yes phase switching is enabled and works manually via App Website. Thats whyvit is strange, that it doesn't work in HA!?

**Comment by dupondje** [comment]
> Yes phase switching is enabled and works manually via App Website. Thats whyvit is strange, that it doesn't work in HA!?

Could you try to change https://github.com/dupondje/nrgkick-ha/blob/713abc046e019218043f5d8ee3b8cc0c80fd3c18/custom_components/nrgkick/number.py#L74
To:
```
 api_fn=lambda c, v: c.set("control", "phase_count", int(v)),
```

And see if that works.

**Comment by thecem** [comment]
without PW i´m able to set "aktuelle Ladeleistung", but not phases and not energy limit

**Comment by thecem** [comment]
Logging via debug is not really helpful.

**Comment by thecem** [comment]
Ladepause switch is not representing the status off (switch back on after time) but if you flip it of and on it will be switched on in nrgkick.

**Comment by dupondje** [comment]
I've just pushed a new commit which contains some fixes :)
Please open a new bug for each issue if you still hit some, otherwise the overview is gone.

Thanks!

**Comment by thecem** [comment]
So I set up wireshark and tested the request and found the problem:

this is relevant in https://github.com/dupondje/nrgkick-ha/commit/713abc046e019218043f5d8ee3b8cc0c80fd3c18

request:

`http://192.168.1.2/control?energy_limit=35.986`

answer:

```
{
    "Response": "Invalid limit entered, value must be greater or equal than 0Wh and less or equal than 1000000Wh"
}
```

request:

`http://192.168.76.160/control?phase_count=2.0`

answer:

```
{
    "Response": "Invalid phases entered, allowed 1 - 3"
}
```
the request for the switch is coreect: 
`
http://192.168.76.160/control?charge_pause=1`

@dupondje: I hope your fixes take this into account.

**Comment by thecem** [comment]
By the way this response is even not in debug mode pushed to the log.

**Comment by thecem** [comment]
pause switch is still showing wrong stae "on" and value is 0

**Comment by dupondje** [comment]
> pause switch is still showing wrong stae "on" and value is 0

Should be fixed now
